---
- name: launch kvm host instance
  amazon.aws.ec2_instance:
    name: "{{ infra_ec2_project_tag }}-kvm"
    instance_type: "{{ infra_ec2_kvm_instance_type }}"
    image_id: "{{ infra_ec2_rhel9_ami_id }}"
    key_name: "{{ infra_ec2_key_name }}"
    region: "{{ infra_ec2_region }}"
    vpc_subnet_id: "{{ private_subnet_id }}"
    security_groups:
      - "{{ sg_kvm_id }}"
      - "{{ sg_ocp_nodes_id }}"
    network:
      assign_public_ip: false
      private_ip_address: "{{ infra_ec2_kvm_ip }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: "{{ infra_ec2_kvm_root_volume_size }}"
          volume_type: gp3
          delete_on_termination: true
      - device_name: /dev/sdf
        ebs:
          volume_size: "{{ infra_ec2_kvm_data_volume_size }}"
          volume_type: gp3
          delete_on_termination: true
    tags:
      Project: "{{ infra_ec2_project_tag }}"
      Environment: sandbox
      sandbox_role: kvm
    wait: true
    state: running
  register: infra_ec2_kvm_result

- name: get kvm host instance details
  amazon.aws.ec2_instance_info:
    region: "{{ infra_ec2_region }}"
    instance_ids:
      - "{{ infra_ec2_kvm_result.instances[0].instance_id }}"
  register: infra_ec2_kvm_info

- name: assign secondary private ips for ocp vms and vips
  amazon.aws.ec2_eni:
    eni_id: "{{ infra_ec2_kvm_info.instances[0].network_interfaces[0].network_interface_id }}"
    region: "{{ infra_ec2_region }}"
    secondary_private_ip_addresses: "{{ infra_ec2_kvm_secondary_ips }}"
    state: present
  register: infra_ec2_kvm_eni_result

- name: disable source destination check on kvm host eni
  amazon.aws.ec2_eni:
    eni_id: "{{ infra_ec2_kvm_info.instances[0].network_interfaces[0].network_interface_id }}"
    region: "{{ infra_ec2_region }}"
    source_dest_check: false
    state: present
