---
- name: launch services instance
  amazon.aws.ec2_instance:
    name: "{{ infra_ec2_project_tag }}-services"
    instance_type: "{{ services_instance_type }}"
    image_id: "{{ infra_ec2_rhel9_ami_id }}"
    key_name: "{{ infra_ec2_key_name }}"
    region: "{{ infra_ec2_region }}"
    vpc_subnet_id: "{{ private_subnet_id }}"
    security_groups:
      - "{{ sg_services_id }}"
    network:
      assign_public_ip: false
      private_ip_address: "{{ services_private_ip }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: "{{ services_root_volume_size }}"
          volume_type: gp3
          delete_on_termination: true
    tags:
      Project: "{{ infra_ec2_project_tag }}"
      Environment: sandbox
      sandbox_role: services
    wait: true
    state: running
  register: infra_ec2_services_result

- name: launch registry instance
  amazon.aws.ec2_instance:
    name: "{{ infra_ec2_project_tag }}-registry"
    instance_type: "{{ registry_instance_type }}"
    image_id: "{{ infra_ec2_rhel9_ami_id }}"
    key_name: "{{ infra_ec2_key_name }}"
    region: "{{ infra_ec2_region }}"
    vpc_subnet_id: "{{ private_subnet_id }}"
    security_groups:
      - "{{ sg_registry_id }}"
    network:
      assign_public_ip: false
      private_ip_address: "{{ registry_private_ip }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: "{{ registry_root_volume_size }}"
          volume_type: gp3
          delete_on_termination: true
      - device_name: /dev/sdf
        ebs:
          volume_size: "{{ registry_data_volume_size }}"
          volume_type: gp3
          delete_on_termination: true
    tags:
      Project: "{{ infra_ec2_project_tag }}"
      Environment: sandbox
      sandbox_role: registry
    wait: true
    state: running
  register: infra_ec2_registry_result
