---
galaxy_info:
  role_name: bastion_haproxy
  description: HAProxy L4 reverse proxy for OCP API and apps ingress
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
