---
bastion_repo_port: "{{ bastion_repo_port }}"
bastion_repo_base_dir: /var/www/html/repos
bastion_repo_name: rhel9-local

bastion_repo_packages:
  # STIG/hardening
  - openscap-scanner
  - scap-security-guide
  - libxslt
  # DNS
  - bind
  - bind-utils
  # NTP
  - chrony
  # General utilities
  - tmux
  - tcpdump
  - nmap-ncat
