---
galaxy_info:
  author: bgregori
  license: GPL-3.0-or-later
  role_name: infra_security_groups
  description: Create security groups for bastion, services, registry, and OCP nodes
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
