---
plugin: amazon.aws.aws_ec2
regions:
  - "{{ lookup('env', 'AWS_REGION') | default('us-east-2', true) }}"
filters:
  tag:Project: disconnected-sandbox
  instance-state-name: running
keyed_groups:
  - key: tags.sandbox_role
    prefix: role
    separator: "_"
groups:
  private_hosts: tags.sandbox_role != 'bastion'
hostnames:
  - private-ip-address
compose:
  ansible_host: public_ip_address | default(private_ip_address)
