---
galaxy_info:
  author: bgregori
  license: GPL-3.0-or-later
  role_name: infra_vpc
  description: Provision VPC, subnets, IGW, and route tables for disconnected sandbox
  min_ansible_version: "2.15"
  platforms:
    - name: GenericCloud
      versions:
        - all
dependencies: []
