---
galaxy_info:
  author: bgregori
  license: GPL-3.0-or-later
  role_name: rhel_hardening
  description: Enable FIPS 140-3 and apply DISA STIG on RHEL 9 hosts
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
