---
infra_security_groups_region: "{{ aws_region }}"
infra_security_groups_project_tag: "{{ project_tag }}"
infra_security_groups_vpc_id: "{{ vpc_id }}"
infra_security_groups_private_subnet_cidr: "{{ private_subnet_cidr }}"
infra_security_groups_vpc_cidr: "{{ vpc_cidr }}"
infra_security_groups_admin_cidr: "{{ admin_cidr }}"
infra_security_groups_services_ip: "{{ services_private_ip }}"
infra_security_groups_registry_ip: "{{ registry_private_ip }}"
infra_security_groups_bastion_ip: "{{ bastion_private_ip }}"
infra_security_groups_bastion_repo_port: "{{ bastion_repo_port }}"
infra_security_groups_enable_kvm: "{{ enable_kvm_host }}"
infra_security_groups_kvm_ip: "{{ kvm_private_ip }}"
infra_security_groups_redfish_port: "{{ redfish_port }}"
