---
galaxy_info:
  author: bgregori
  license: GPL-3.0-or-later
  role_name: infra_route53
  description: Create Route53 A records for OCP API and wildcard apps
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
