---
bind_dns_listen_ip: "{{ services_private_ip }}"
bind_dns_allow_query_cidr: "{{ vpc_cidr }}"
bind_dns_zone: "{{ cluster_domain }}"
bind_dns_reverse_zone_private: "2.0.10.in-addr.arpa"
bind_dns_reverse_zone_public: "1.0.10.in-addr.arpa"
bind_dns_bastion_repo_url: "http://{{ bastion_private_ip }}:{{ bastion_repo_port }}/rhel9-local"

bind_dns_records:
  - name: api
    ip: "{{ ocp_node_ips[0] }}"
  - name: api-int
    ip: "{{ ocp_node_ips[0] }}"
  - name: "*.apps"
    ip: "{{ ocp_node_ips[0] }}"
  - name: services
    ip: "{{ services_private_ip }}"
  - name: registry
    ip: "{{ registry_private_ip }}"
  - name: bastion
    ip: "{{ bastion_private_ip }}"
  - name: node-0
    ip: "{{ ocp_node_ips[0] }}"
  - name: node-1
    ip: "{{ ocp_node_ips[1] }}"
  - name: node-2
    ip: "{{ ocp_node_ips[2] }}"
